# configure updates globally
# default: all
# allowed: all, insecure, False
update: all

# configure dependency pinning globally
# default: True
# allowed: True, False
pin: True

# add a label to pull requests, default is not set
# requires private repo permissions, even on public repos
# default: empty
label_prs: update

# Won't work as PyUp doesn't have native support for poetry
requirements:
  - "requirements.txt"
  - "docs/requirements.txt"
  - "{{cookiecutter.project_slug}}/requirements/local.txt"
  - "{{cookiecutter.project_slug}}/requirements/production.txt"
